apiVersion: v1
kind: Service
metadata:
  name: bizbook-crm-d-staging
  namespace: colossus-bizbook-crm-d-staging
  labels:
    app: bizbook-crm-d-staging
    managed-by: colossus
spec:
  type: ClusterIP
  selector:
    app: bizbook-crm-d-staging
  ports:
    - port: 80
      targetPort: 80
